### ISSUE TITLE
Just use the CLI for validation and call it a day

### ISSUE THREAD

**Issue by mfocko** [alpa-team/pre-commit-hooks#1]
You can run programs from shell in pre-commit, just make sure they are installed (I don't think you can get rid of the dependencies anyways).

CLI command: https://packit.dev/docs/cli/validate-config/

**Comment by nikromen** [comment]
https://github.com/alpa-team/pre-commit-hooks/blob/main/pre_commit_hooks/check_packit_file.py#L17
